# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
#slack
Slack_API: "https://hooks.slack.com/services/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"
#Tiwlio               
account_sid: "ACcaad04a625fd3172925140a6a3ec87a3"
auth_token: "e64e4ca8499c6d9f6d8cbdccbc7efe2b"
#IBM Watson
TEXT_TO_SPEECH_IAM_APIKEY: "8ulvC5DjztsG_4KuGw23QMXgW9yLX3WbP8SSwLq8RLNu"
TEXT_TO_SPEECH_URL: "https://api.us-south.text-to-speech.watson.cloud.ibm.com/instances/9f191e7d-16d5-4606-8c7b-8eeb63cca967"
#Sendgrid
SENDGRID_API_KEY: "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"
#Zendesk
ZENDESK_URL: "https://dondongnguyenhelp.zendesk.com/api/v2"
ZENDESK_USERNAME: "don_nguyen2001@yahoo.com"
ZENDESK_TOKEN: "N0Jtm8o4FTIQJEbNJiKH72q52PM2KPiDyo3lzPOl"
#Dropbox
DROPBOX_OAUTH_BEARER: "6d3b59Y8GE4AAAAAAAAAAa1dkVAWIA6M98cxd2XbcIgUmfDqksou9TSvGvLMsPDF"
#Google map
GOOGLE_MAPS_API_KEY: "AIzaSyAB5RqgmEunQ1OSCUreR9ubyKjQVhevUCk"

