default: &default
 adapter: mysql2
 encoding: utf8
 username: dbmasteruser
 password: hellolove
 host: donnguyen.czfqm6fbqz9o.us-west-1.rds.amazonaws.com
 port: 3306

development:
 <<: *default
 database: donnguyen

default: &postgresql
  adapter: postgresql
  encoding: unicode
  username: dbmasteruser
  password: hellolove
  host: postgresql.czfqm6fbqz9o.us-west-1.rds.amazonaws.com

warehouse_development:
  <<: *postgresql
  database: postgresql